# Generated by Django 3.2.22 on 2023-11-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
